name: "Deploy CDK Stack"
description: "Deploys a CDK stack with validation and reporting"
branding:
  icon: "arrow-up-circle"
  color: "blue"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "22"
  cdk-version:
    description: "AWS CDK version to install"
    required: true
  aws-region:
    description: "AWS Region"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true
  working-directory:
    description: "Working directory for npm commands"
    required: false
    default: "."
  stack-name:
    description: "Name of the stack to deploy"
    required: true

outputs:
  deployment-status:
    description: "Status of the deployment (success/failure)"
    value: ${{ steps.deploy.outputs.status }}

runs:
  using: composite
  steps:
    # Step 1
    - name: Download Synthesized Template
      uses: actions/download-artifact@v4
      with:
        name: cdk-synth
        path: ${{ inputs.working-directory }}/cdk.out

    # Step 2
    - name: Prepare CDK Environment
      shell: bash
      run: mv ./cdk.out/package*.json .

    # Step 3
    - name: Setup CDK Environment
      uses: banboniera/setup-cdk@v1
      with:
        node-version: ${{ inputs.node-version }}
        cdk-version: ${{ inputs.cdk-version }}
        aws-region: ${{ inputs.aws-region }}
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        working-directory: ${{ inputs.working-directory }}

    # Step 4
    - name: Validate Stack
      shell: bash
      run: |
        echo "::group::Stack Validation"
        if ! cdk diff ${{ inputs.stack-name }} --app ${{ inputs.working-directory }}/cdk.out; then
          echo "::error::Stack validation failed - detected unexpected changes"
          exit 1
        fi
        echo "::endgroup::"

    # Step 5
    - name: Deploy Stack
      id: deploy
      shell: bash
      run: |
        echo "START_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

        if cdk deploy ${{ inputs.stack-name }} --require-approval never --app ${{ inputs.working-directory }}/cdk.out; then
          STATUS="success"
        else
          STATUS="failure"
          echo "status=${STATUS}" >> $GITHUB_OUTPUT
          END_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo "END_TIME=${END_TIME}" >> $GITHUB_OUTPUT
          exit 1
        fi

        echo "status=${STATUS}" >> $GITHUB_OUTPUT
        echo "END_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    # Step 6
    - name: Deployment Summary
      if: always()
      shell: bash
      run: |
        echo "### Stack Deployment: ${{ inputs.stack-name }} :rocket:" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.deploy.outputs.status }}" == "success" ]; then
          echo "- **Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Status**: ❌ Failed" >> $GITHUB_STEP_SUMMARY
        fi

        if [[ "${{ steps.deploy.outputs.START_TIME }}" && "${{ steps.deploy.outputs.END_TIME }}" ]]; then
          start_sec=$(date -d "${{ steps.deploy.outputs.START_TIME }}" +%s)
          end_sec=$(date -d "${{ steps.deploy.outputs.END_TIME }}" +%s)
          duration=$(( end_sec - start_sec ))
          echo "- **Duration**: ${duration} seconds" >> $GITHUB_STEP_SUMMARY
        fi
